{{/*
AgentVault™ Secrets
Secure storage for credentials and sensitive configuration
Author: Dwiref Sharma
Contact: DwirefS@SapientEdge.io
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentvault.fullname" . }}-secrets
  labels:
    {{- include "agentvault.labels" . | nindent 4 }}
type: Opaque
data:
  # Database credentials
  {{- if .Values.postgresql.enabled }}
  postgres-username: {{ .Values.postgresql.auth.username | b64enc }}
  postgres-password: {{ .Values.postgresql.auth.password | b64enc }}
  postgres-database: {{ .Values.postgresql.auth.database | b64enc }}
  {{- end }}
  
  # Redis credentials
  {{- if and .Values.redis.enabled .Values.redis.auth.enabled }}
  redis-password: {{ .Values.redis.auth.password | b64enc }}
  {{- end }}
  
  # Azure AD credentials
  {{- if and .Values.security.authentication.enabled (has "azure-ad" .Values.security.authentication.providers) }}
  azure-ad-tenant-id: {{ .Values.security.authentication.azureAD.tenantId | b64enc }}
  azure-ad-client-id: {{ .Values.security.authentication.azureAD.clientId | b64enc }}
  azure-ad-client-secret: {{ .Values.security.authentication.azureAD.clientSecret | b64enc }}
  {{- end }}
  
  # Azure Service Principal credentials
  azure-subscription-id: {{ .Values.anf.subscriptionId | b64enc }}
  azure-tenant-id: {{ .Values.global.azure.tenantId | default "" | b64enc }}
  azure-client-id: {{ .Values.global.azure.clientId | default "" | b64enc }}
  azure-client-secret: {{ .Values.global.azure.clientSecret | default "" | b64enc }}
  
  # Encryption keys
  {{- if .Values.security.encryption.enabled }}
  master-encryption-key: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  
  # API keys
  webhook-secret: {{ randAlphaNum 32 | b64enc }}
  jwt-secret: {{ randAlphaNum 64 | b64enc }}
  
  # Monitoring credentials
  {{- if .Values.monitoring.enabled }}
  monitoring-username: {{ "admin" | b64enc }}
  monitoring-password: {{ randAlphaNum 16 | b64enc }}
  {{- end }}

---
{{- if .Values.monitoring.enabled }}
# Basic auth secret for monitoring endpoints
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentvault.fullname" . }}-monitoring-auth
  labels:
    {{- include "agentvault.labels" . | nindent 4 }}
type: Opaque
data:
  auth: {{ htpasswd "admin" (randAlphaNum 16) | b64enc }}
{{- end }}

---
{{- if .Values.ingress.enabled }}
# TLS certificate secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentvault.secretName" . }}
  labels:
    {{- include "agentvault.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- if .Values.ingress.tls }}
  {{- range .Values.ingress.tls }}
  {{- if .secretName }}
  # TLS certificate will be managed by cert-manager
  {{- else }}
  {{- include "agentvault.gen-certs" . | nindent 2 }}
  {{- end }}
  {{- end }}
  {{- else }}
  {{- include "agentvault.gen-certs" . | nindent 2 }}
  {{- end }}
{{- end }}

---
{{- if .Values.image.pullSecrets }}
# Docker registry credentials
apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  labels:
    {{- include "agentvault.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"%s":{"username":"%s","password":"%s","auth":"%s"}}}` .Values.image.registry .Values.global.azure.clientId .Values.global.azure.clientSecret (printf "%s:%s" .Values.global.azure.clientId .Values.global.azure.clientSecret | b64enc) | b64enc }}
{{- end }}

---
{{- range $name, $data := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "agentvault.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $data.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}

---
# Azure Key Vault CSI Driver SecretProviderClass
{{- if .Values.security.encryption.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "agentvault.fullname" . }}-keyvault
  labels:
    {{- include "agentvault.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.serviceAccount.annotations.azure.workload.identity/client-id | quote }}
    keyvaultName: {{ .Values.security.encryption.keyVaultName | quote }}
    cloudName: ""
    objects: |
      array:
        - |
          objectName: master-key
          objectType: key
          objectVersion: ""
        - |
          objectName: backup-encryption-key
          objectType: key
          objectVersion: ""
        - |
          objectName: database-encryption-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: api-signing-key
          objectType: secret
          objectVersion: ""
    tenantId: {{ .Values.global.azure.tenantId | quote }}
  secretObjects:
    - secretName: {{ include "agentvault.fullname" . }}-keyvault-secrets
      type: Opaque
      data:
        - objectName: master-key
          key: master-key
        - objectName: backup-encryption-key
          key: backup-key
        - objectName: database-encryption-key
          key: db-key
        - objectName: api-signing-key
          key: api-key
{{- end }}