apiVersion: v2
name: agentvault
description: |
  AgentVault™ - Enterprise AI Agent Storage Platform
  Production-ready Helm chart for deploying AgentVault with Azure NetApp Files,
  distributed caching, ML optimization, and complete observability.
  
  Author: Dwiref Sharma
  Contact: DwirefS@SapientEdge.io

type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - ai
  - agents
  - storage
  - azure
  - netapp
  - machine-learning
  - enterprise

home: https://github.com/DwirefS/AgentVault
sources:
  - https://github.com/DwirefS/AgentVault

maintainers:
  - name: Dwiref Sharma
    email: DwirefS@SapientEdge.io

annotations:
  category: Database
  licenses: MIT

dependencies:
  - name: redis
    version: 17.15.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  
  - name: prometheus
    version: 25.3.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  
  - name: grafana
    version: 7.0.19
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
  
  - name: jaeger
    version: 0.71.14
    repository: https://jaegertracing.github.io/helm-charts
    condition: monitoring.jaeger.enabled